#!/usr/bin/env python3
"""
Generate sql/15_parity_views_unquoted.sql — unquoted-uppercase views over the
five parity fact tables, for Cortex Analyst / Cortex Agents.

Why (measured 2026-09-03, phase 2 O5): the parity tables in BASEBALL.WAX_BASEBALL
carry case-preserved lowercase column names from the Parquet INFER_SCHEMA load, so
every physical column is a quoted identifier ("game_id"). Plain SEMANTIC_VIEW() SQL
accepts that (the parity harness passes 28/28), but Cortex Analyst serializes a
semantic view to its YAML model and rejects quoted names outright:

    error_code 392700: invalid column name "game_id": name must start with an
    underscore or a letter, and only contain letters, underscores, digits, $

Two front doors into one semantic view; one validates it, one doesn't. The fix
that touches nothing upstream: views with unquoted UPPERCASE columns, and the
semantic view (sql/20) pointed at the views instead of the tables. Logical
dimension/metric names don't change, so the harness is unaffected.

This script reads the live column lists (DESCRIBE TABLE) and writes the DDL — rerun
it after any parity reload that adds a column. Never hand-edit the output.

    py scripts/build_unquoted_views.py            # writes sql/15_parity_views_unquoted.sql
    snow sql -c wax_baseball_key -f sql/15_parity_views_unquoted.sql
"""

from __future__ import annotations

import json
import pathlib
import subprocess

CONNECTION = "wax_baseball_key"
SOURCE_SCHEMA = "BASEBALL.WAX_BASEBALL"
TARGET_SCHEMA = "BASEBALL.SEMANTICS"
TABLES = [
    "FCT_ATTENDED_GAMES",
    "FCT_PLAYS",
    "FCT_GAME_ATTENDEE",
    "FCT_ATTENDED_TEAM_GAMES",
    "FCT_HOF_SIGHTINGS",
]
OUT = pathlib.Path(__file__).resolve().parent.parent / "sql" / "15_parity_views_unquoted.sql"


def describe(table: str) -> list[str]:
    out = subprocess.run(
        ["snow", "sql", "-c", CONNECTION, "--format", "json", "-q", f"DESCRIBE TABLE {SOURCE_SCHEMA}.{table}"],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    if out.returncode != 0:
        raise RuntimeError(out.stderr.strip()[:400])
    return [r["name"] for r in json.loads(out.stdout)]


def main() -> None:
    lines = [
        "-- GENERATED by scripts/build_unquoted_views.py -- do not hand-edit.",
        "-- Unquoted-uppercase views over the parity tables so Cortex Analyst can",
        "-- validate the semantic view (quoted lowercase columns fail error 392700).",
        "",
        "USE ROLE ACCOUNTADMIN;",
        "USE WAREHOUSE WAX_WH;",
        "",
    ]
    for t in TABLES:
        cols = describe(t)
        select = ",\n".join(f'    "{c}" AS {c.upper()}' for c in cols)
        lines += [
            f"CREATE OR REPLACE VIEW {TARGET_SCHEMA}.{t}",
            f"  COMMENT = 'Unquoted-uppercase view over {SOURCE_SCHEMA}.{t} for Cortex Analyst (generated).'",
            "AS SELECT",
            select,
            f"FROM {SOURCE_SCHEMA}.{t};",
            "",
        ]
        print(f"{t}: {len(cols)} columns")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
