CREATE DATABASE IF NOT EXISTS BASEBALL;
CREATE SCHEMA IF NOT EXISTS BASEBALL.LAHMAN_RAW;

CREATE OR REPLACE FILE FORMAT BASEBALL.LAHMAN_RAW.csv_with_header
  TYPE = 'CSV'
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  ENCODING = 'UTF8'
  SKIP_BYTE_ORDER_MARK = TRUE
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  REPLACE_INVALID_CHARACTERS = TRUE
  COMPRESSION = AUTO;
