CREATE DATABASE IF NOT EXISTS BASEBALL;
CREATE SCHEMA IF NOT EXISTS BASEBALL.WAX_BASEBALL;

CREATE OR REPLACE FILE FORMAT BASEBALL.WAX_BASEBALL.parquet_format
  TYPE = 'PARQUET'
  COMPRESSION = AUTO;
