-- GENERATED by scripts/build_unquoted_views.py -- do not hand-edit.
-- Unquoted-uppercase views over the parity tables so Cortex Analyst can
-- validate the semantic view (quoted lowercase columns fail error 392700).

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WAX_WH;

CREATE OR REPLACE VIEW BASEBALL.SEMANTICS.FCT_ATTENDED_GAMES
  COMMENT = 'Unquoted-uppercase view over BASEBALL.WAX_BASEBALL.FCT_ATTENDED_GAMES for Cortex Analyst (generated).'
AS SELECT
    "game_id" AS GAME_ID,
    "game_date" AS GAME_DATE,
    "home_team_id_retro" AS HOME_TEAM_ID_RETRO,
    "away_team_id_retro" AS AWAY_TEAM_ID_RETRO,
    "park_id" AS PARK_ID,
    "wax_game_id" AS WAX_GAME_ID,
    "game_type_wax" AS GAME_TYPE_WAX,
    "venue_wax" AS VENUE_WAX,
    "city" AS CITY,
    "state" AS STATE,
    "home_team_name" AS HOME_TEAM_NAME,
    "away_team_name" AS AWAY_TEAM_NAME,
    "home_team_id_wax" AS HOME_TEAM_ID_WAX,
    "away_team_id_wax" AS AWAY_TEAM_ID_WAX,
    "home_score" AS HOME_SCORE,
    "away_score" AS AWAY_SCORE,
    "innings_played" AS INNINGS_PLAYED,
    "game_length_minutes" AS GAME_LENGTH_MINUTES,
    "day_of_week" AS DAY_OF_WEEK,
    "start_time" AS START_TIME,
    "day_night_code" AS DAY_NIGHT_CODE,
    "is_doubleheader" AS IS_DOUBLEHEADER,
    "is_allstar" AS IS_ALLSTAR,
    "game_type_retro" AS GAME_TYPE_RETRO,
    "temperature_f" AS TEMPERATURE_F,
    "wind_direction_code" AS WIND_DIRECTION_CODE,
    "wind_speed_mph" AS WIND_SPEED_MPH,
    "precipitation_code" AS PRECIPITATION_CODE,
    "sky_code" AS SKY_CODE,
    "attendance" AS ATTENDANCE,
    "home_plate_umpire" AS HOME_PLATE_UMPIRE,
    "winning_pitcher_id" AS WINNING_PITCHER_ID,
    "losing_pitcher_id" AS LOSING_PITCHER_ID,
    "save_pitcher_id" AS SAVE_PITCHER_ID,
    "was_attended" AS WAS_ATTENDED,
    "winning_team_id" AS WINNING_TEAM_ID,
    "score_margin" AS SCORE_MARGIN,
    "is_yankees_game" AS IS_YANKEES_GAME,
    "home_team_won" AS HOME_TEAM_WON
FROM BASEBALL.WAX_BASEBALL.FCT_ATTENDED_GAMES;

CREATE OR REPLACE VIEW BASEBALL.SEMANTICS.FCT_PLAYS
  COMMENT = 'Unquoted-uppercase view over BASEBALL.WAX_BASEBALL.FCT_PLAYS for Cortex Analyst (generated).'
AS SELECT
    "game_id" AS GAME_ID,
    "event_id" AS EVENT_ID,
    "game_date" AS GAME_DATE,
    "was_attended" AS WAS_ATTENDED,
    "home_team_id_retro" AS HOME_TEAM_ID_RETRO,
    "away_team_id_retro" AS AWAY_TEAM_ID_RETRO,
    "park_id" AS PARK_ID,
    "venue_wax" AS VENUE_WAX,
    "is_yankees_game" AS IS_YANKEES_GAME,
    "inning" AS INNING,
    "is_bottom_half_inning" AS IS_BOTTOM_HALF_INNING,
    "outs_before" AS OUTS_BEFORE,
    "outs_on_play" AS OUTS_ON_PLAY,
    "balls" AS BALLS,
    "strikes" AS STRIKES,
    "pitch_sequence" AS PITCH_SEQUENCE,
    "count_text" AS COUNT_TEXT,
    "batter_id" AS BATTER_ID,
    "pitcher_id" AS PITCHER_ID,
    "batter_hand" AS BATTER_HAND,
    "pitcher_hand" AS PITCHER_HAND,
    "batter_lineup_slot" AS BATTER_LINEUP_SLOT,
    "event_code" AS EVENT_CODE,
    "event_text" AS EVENT_TEXT,
    "hit_code" AS HIT_CODE,
    "runs_on_play" AS RUNS_ON_PLAY,
    "rbi" AS RBI,
    "batted_ball_type" AS BATTED_BALL_TYPE,
    "batted_ball_location" AS BATTED_BALL_LOCATION,
    "away_score_before" AS AWAY_SCORE_BEFORE,
    "home_score_before" AS HOME_SCORE_BEFORE,
    "is_leadoff" AS IS_LEADOFF,
    "is_pinch_hitter" AS IS_PINCH_HITTER,
    "is_double_play" AS IS_DOUBLE_PLAY,
    "is_triple_play" AS IS_TRIPLE_PLAY
FROM BASEBALL.WAX_BASEBALL.FCT_PLAYS;

CREATE OR REPLACE VIEW BASEBALL.SEMANTICS.FCT_GAME_ATTENDEE
  COMMENT = 'Unquoted-uppercase view over BASEBALL.WAX_BASEBALL.FCT_GAME_ATTENDEE for Cortex Analyst (generated).'
AS SELECT
    "wax_game_id" AS WAX_GAME_ID,
    "attendee_key" AS ATTENDEE_KEY,
    "attendee_name" AS ATTENDEE_NAME,
    "attendee_type" AS ATTENDEE_TYPE,
    "game_date" AS GAME_DATE,
    "is_yankees_game" AS IS_YANKEES_GAME,
    "game_type_wax" AS GAME_TYPE_WAX,
    "source_column" AS SOURCE_COLUMN,
    "source_position" AS SOURCE_POSITION
FROM BASEBALL.WAX_BASEBALL.FCT_GAME_ATTENDEE;

CREATE OR REPLACE VIEW BASEBALL.SEMANTICS.FCT_ATTENDED_TEAM_GAMES
  COMMENT = 'Unquoted-uppercase view over BASEBALL.WAX_BASEBALL.FCT_ATTENDED_TEAM_GAMES for Cortex Analyst (generated).'
AS SELECT
    "game_id" AS GAME_ID,
    "wax_game_id" AS WAX_GAME_ID,
    "game_date" AS GAME_DATE,
    "game_type_wax" AS GAME_TYPE_WAX,
    "venue_wax" AS VENUE_WAX,
    "is_yankees_game" AS IS_YANKEES_GAME,
    "team_id" AS TEAM_ID,
    "opponent_team_id" AS OPPONENT_TEAM_ID,
    "is_home" AS IS_HOME,
    "team_score" AS TEAM_SCORE,
    "opponent_score" AS OPPONENT_SCORE,
    "winning_team_id" AS WINNING_TEAM_ID,
    "is_decided" AS IS_DECIDED,
    "team_won" AS TEAM_WON
FROM BASEBALL.WAX_BASEBALL.FCT_ATTENDED_TEAM_GAMES;

CREATE OR REPLACE VIEW BASEBALL.SEMANTICS.FCT_HOF_SIGHTINGS
  COMMENT = 'Unquoted-uppercase view over BASEBALL.WAX_BASEBALL.FCT_HOF_SIGHTINGS for Cortex Analyst (generated).'
AS SELECT
    "player_id" AS PLAYER_ID,
    "player_name" AS PLAYER_NAME,
    "retro_id" AS RETRO_ID,
    "induction_year" AS INDUCTION_YEAR,
    "games_seen" AS GAMES_SEEN,
    "plays_seen" AS PLAYS_SEEN,
    "first_seen_date" AS FIRST_SEEN_DATE,
    "last_seen_date" AS LAST_SEEN_DATE,
    "seen_batting" AS SEEN_BATTING,
    "seen_pitching" AS SEEN_PITCHING
FROM BASEBALL.WAX_BASEBALL.FCT_HOF_SIGHTINGS;
